language: python
python:
  - "2.7"
# Make sure the Ubuntu 12.04 system packages are installed for the tests.
virtualenv:
  system_site_packages: true
# Note that yeadon will not install without pyyaml installed first. See yeadon
# issue #111.
before_install:
  - pip uninstall -y numpy
  - sudo apt-get install -y -qq python-setuptools python-numpy python-scipy python-matplotlib python-tables python-yaml python-nose python-coverage
  - pip install "DynamicistToolKit>=0.3.4"
  - pip install "uncertainties>=2.0.0"
  - pip install "yeadon>=1.1.1"
  - pip install "BicycleParameters>-0.2.0"
  - pip freeze
install:
  - python setup.py install
script: nosetests -v --with-coverage --cover-package=bicycleparameters
