language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels moorepants
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION setuptools pip numpy scipy matplotlib pyyaml pytables nose coverage dynamicisttoolkit uncertainties
  - source activate test-environment
  - pip install yeadon
  - pip install BicycleParameters
install:
  - python setup.py install
script:
  - nosetests -v --with-coverage --cover-package=bicycledataprocessor
