addpath('hdf5matlab')

load(['..' filesep '..' filesep 'BicycleDAQ' filesep 'data' filesep '00157.mat'])

hdf5save('00157.h5', ...
         'InputPairs', 'InputPairs', ...
         'NIData', 'NIData', ...
         'VNavCols', 'VNavCols', ...
         'VNavData', 'VNavData', ...
         'VNavDataText', 'VNavDataText', ...
         'par', 'par')
