%addpath('hdf5matlab')

load(['..' filesep '..' filesep 'BicycleDAQ' filesep 'data' filesep '00170.mat'])

hdf5save('00170.h5', ...
         'InputPairs', 'InputPairs', ...
         'NIData', 'NIData', ...
         'par', 'par')
